### PR TITLE
Properly restart repo if .py files are not associated with Python

### PR DESCRIPTION
**Pull request by sschuberth**
On Windows, you cannot directly execute .py files unless they are
associated with Python. When using Python from Cygwin or MSYS(2) this
typically is not the case. Solve this by explicitly prefixing the
subprocess call with the Python interpreter executable.

### CODE REVIEW

**Comment by mputz86** [comment]
Thanks sschuberth for your fix. We are not maintaining this specific master-branch anymore. But the problem is already fixed on the stable branch.
Could you verify if the problem is fixed for you on the stable branch?

**Comment by sschuberth** [comment]
Hi @mputz86. From looking at [the code](https://github.com/esrlabs/git-repo/blob/stable/main.py#L528) in `stable` the issue indeed seems to be fixed there. However, on the one hand you're saying that `master` is not maintained anymore, and on the other hand you're also saying that `stable` (despite it's name) is not ready for production use yet. So what should we use for production right now?

I acknowledge that you don't want to put more work into `master`, but accepting simple PRs should still be fine, or?

**Comment by mputz86** [comment]
Hey sschuberth - you are completely right, I am right now trying to clarify this confusion :). We will set stable-branch to default branch, add a warning for the old master-branch, and remove the "not yet ready" message on stable :).
The real reason for not wanting to change anything on master is to not break it :). Anyway, I am not fair if I do not appreciate your work and merge your change, it is on the list now.

**Comment by sschuberth** [comment]
> Anyway, I am not fair if I do not appreciate your work and merge your change, it is on the list now.

Thanks :-)

**Comment by mputz86** [comment]
Thank you too ! Fixed and commited, please verify :).
 + tried to "fix" confusion regarding the branches, clearer? (elsewise thats and issue ;))

**Pull request closed without merging**
